version: "3"

services:
  reverse_nginx:
    container_name: reverse_nginx
    image: nginx:1.23-alpine
    networks:
      - reverse
    ports:
      - "80:80"
    volumes:
      - ./reverse_proxy/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./reverse_proxy/static:/usr/share/nginx/html
    restart: always
    depends_on:
      - ted_search

  ted_search:
    container_name: ted_search
    image: 644435390668.dkr.ecr.eu-central-1.amazonaws.com/adam-ted:latest
    networks:
      - reverse
      - cache
    restart: always

  memcached:
    container_name: memcached
    image: memcached:1.6.17-alpine
    command: memcached -m 64
    ports:
      - "11211:11211"
    networks:
      - cache
    restart: always

networks:
  reverse:
    driver: bridge
  cache:
    driver: bridge